### ISSUE TITLE
ESP8266 and mqtt_as

### ISSUE THREAD

**Issue by rainergo** [peterhinch/micropython-mqtt#103]
Hi, 
you wrote:

_"copy mqtt_as.py to esp8266/modules in the source tree, build and deploy."_

I am new to all this. Could you provide a step-by-step explanation of how I can do the above?

Thanks.

**Comment by peterhinch** [comment]
See [official docs](https://github.com/micropython/micropython/tree/master/ports/esp8266) also [here](http://docs.micropython.org/en/latest/reference/manifest.html).

**Comment by rainergo** [comment]
Thank you Peter!
For the Germany-speaking community, I found some useful tutorials on youtube:
- Micropython erweitern: Teil 1 "Welche Möglichkeiten gibt es?": https://www.youtube.com/watch?v=TDgrecV4wJo
- Micropython erweitern: Teil 2 "Eigene Module im User Filesystem": https://www.youtube.com/watch?v=2pnBpUKG8Ss
- Micropython erweitern: Teil 3 "Eigene Frozen Modules erstellen": https://www.youtube.com/watch?v=opaVzEg-rkg
