### ISSUE TITLE
secure connection with mosquitto_sub

### ISSUE THREAD

**Issue by gmrza** [peterhinch/micropython-mqtt#104]
In tls.py you made the comment that you have not worked out yet how to get mosquitto_sub to use a secure connection.

I am currently using tls with username/password auth, using the following format with mosquitto_sub:

`mosquitto_sub -h <my local mosquitto server> -t result -u <username> -P <password> -p 8883`

**Comment by peterhinch** [comment]
Thanks for that, I'll update the code comment.
