### ISSUE TITLE
where is heartbeat() awaited

### ISSUE THREAD

**Issue by investigatronica** [peterhinch/micropython-mqtt#108]
I'm relatively new with asyncio and I'm trying to understand your code.

I can't figure out when/where asyncio.create_task(heartbeat()) is awaited or which loop it belongs to?

https://github.com/peterhinch/micropython-mqtt/blob/94b97f57c7bc4d56fe5edb3106f6ea06c84080ac/mqtt_as/clean.py#L64

**Comment by peterhinch** [comment]
A task instantiated by `create_task()` will run until it's terminated or is cancelled. There is a single event loop, but normally you can regard it as a `uasyncio` internal object. Most modern `uasyncio` code does not need to reference it.
