### ISSUE TITLE
File "mqtt_as.py", line 622, in connect TypeError: can't convert str to int

### ISSUE THREAD

**Issue by ruben-mar** [peterhinch/micropython-mqtt#114]
Fresh new pull today, with mqtt_local.py configured in a Pico, when running the [Example Usage](https://github.com/peterhinch/micropython-mqtt/blob/master/mqtt_as/README.md#23-example-usage) code I get:

> ```
> >>> %Run -c $EDITOR_CONTENT
> Checking WiFi integrity.
> Got reliable connection
> Traceback (most recent call last):
>   File "<stdin>", line 35, in <module>
>   File "uasyncio/core.py", line 1, in run
>   File "uasyncio/core.py", line 1, in run_until_complete
>   File "uasyncio/core.py", line 1, in run_until_complete
>   File "<stdin>", line 20, in main
>   File "mqtt_as.py", line 622, in connect
> TypeError: can't convert str to int
> ```

When running [range.py](https://github.com/peterhinch/micropython-mqtt/blob/master/mqtt_as/range.py) the console output is:

> ```>>> %Run -c $EDITOR_CONTENT
> Checking WiFi integrity.
> Got reliable connection
> Traceback (most recent call last):
>   File "<stdin>", line 78, in <module>
>   File "uasyncio/core.py", line 1, in run
>   File "uasyncio/core.py", line 1, in run_until_complete
>   File "uasyncio/core.py", line 1, in run_until_complete
>   File "<stdin>", line 54, in main
>   File "mqtt_as.py", line 622, in connect
> TypeError: can't convert str to int
> ```

- mqtt_as.py VERSION = (0, 7, 0)
- The Python language version 3.4.0; MicroPython v1.20.0 on 2023-04-26
- platform rp2
- Implementation machine = Raspberry Pi Pico W with RP2040
- Thonny v. 4.0.2

**Comment by peterhinch** [comment]
I can't replicate this. I use `mpremote` rather than Thonny, but I don't think this is a Thonny issue. Here is my traceback
```python
MPY: soft reboot
MicroPython v1.20.0 on 2023-04-26; Raspberry Pi Pico W with RP2040
Type "help()" for more information.
>>> import range_ex
Checking WiFi integrity.
Got reliable connection
Connecting to broker.
Connected to broker.
We are connected to broker.
publish 0
```
The line that is failing is
```python
self._addr = socket.getaddrinfo(self.server, self.port)[0][-1]
```
Are you sure your server address is correct? You might like to use `ping` to check this.

**Comment by ruben-mar** [comment]
Now, this is embarrassing, I assigned the port as a string. I am not excused by having declared the IP address of the server as a string
`"server": '192.168.1.139',`
followed by the port also as a string
`"port": '1883',`
because the default value of port is an integer 0 all right
`"port": 0,`

Both examples works now. Apologies and thank you.
