### ISSUE TITLE
publish to broker on an event trigger.

### ISSUE THREAD

**Issue by davidecat** [peterhinch/micropython-mqtt#120]
Hello, first of all thank you for your work!
Is there any example on how to use it to publish to the broker on an event trigger?
Im testing it with 5 RPICOW with IR sensor to 1 RPIZero2 with mosquitto.
Thank you again!

edit:
Just to give some further info, i'm testing mqtt_as cause the official driver give me a weird behaviour. Using multiple publishers the first message of a new publisher is lost. I mean: 1 sends correctly, 1 resends correctly, 2 sends and mosquitto dont get is, 2 resends and its correct. if 1 sends again, the first is lost, the second is correct...

**Comment by peterhinch** [comment]
If you look at [this example code](https://github.com/peterhinch/micropython-mqtt/blob/17782357473e28ce29c16223960e541d9cbfa215/mqtt_as/range.py#L62) the `main` task waits for a time before publishing. You could replace that with a wait on anything: an `Event` instance, a pin change, or whatever.

**Comment by davidecat** [comment]
Thank you @peterhinch, it works like a charm!
