### ISSUE TITLE
Esp8266 for wifi and mqtt

### ISSUE THREAD

**Issue by beetlegigg** [peterhinch/micropython-mqtt#138]
Hello Peter,   before the picoW came out I'm sure I was using some of your mqtt libraries that used an esp8266 as the wifi for the pico and the communication twixt the two was via SPI.   I think you had some similar examples for a pyboard and esp8266 combination.

Recently I put the latest mp on a Teensy 4 board that does not have wifi, and I thought of trying to get the old stuff for the esp8266 and pico and having a go at modifying it to work with the esp8266 and Teensy 4 combination.

But I cant seem to find whatever it was I was using back then.  Probably I'm looking in the wrong place.  Can you give my old eyes a break and point me to the right place where this stuff resides.   Many Thanks.

**Comment by peterhinch** [comment]
I recently "retired" the **mqtt-bridge** project. It was developed when ESP8266 was the only MP device with WiFi. Given the limitations of ESP8266 and the benefits at the time of Pyboards it seemed a good idea. Now that WiFi enabled targets are everywhere there seemed little point in continuing to support it. I never saw much evidence of actual users - until now :)

If you want to access it you can clone the repo and check it out:
```bash
$ git checkout b29f5e37f541235664ef9a3d7ffe003d19ffc4fa
```
however I've dismantled my reference setup and won't be able to offer much support.
