### ISSUE TITLE
sense of red wifi LED is backwards w/r/t docs in range demo

### ISSUE THREAD

**Issue by bikeNomad** [peterhinch/micropython-mqtt#143]
Love your code!

The `range` demo says that out-of-range will light the red LED, but in fact the red LED stays on until a failure.

**Comment by ebolisa** [comment]
> Love your code!
> 
> 
> 
> The `range` demo says that out-of-range will light the red LED, but in fact the red LED stays on until a failure.

Not all dev boards are wired the same way. Perhaps you need to invert the command? Where it calls for ON, you send OFF.

**Comment by peterhinch** [comment]
@bikeNomad You are right, thanks for the report. The code comments don't match the code (also `range_ex`). I think it's best to have the LED work as currently, as a "WiFi UP" light. I'll amend the comments.
