### ISSUE TITLE
Losing the connection during the connect handler causes unexpected behaviour

### ISSUE THREAD

**Issue by bobveringa** [peterhinch/micropython-mqtt#147]
While working to validate our MQTTv5 solution, we found a possible bug. 

At the end of the connect procedure, the `_connect_handler` is called. We use this connect handler to subscribe to important topics, this takes a little bit of time. If during this time, connection with the broker is lost, the `_connect_handler` is not canceled. The result of this is that when a connection with the broker is established again, there will be 2 tasks for the `_connect_handler` one that was already in progress and a new one that is started at the end of the connect procedure.

In our case, with MQTTv5, it causes double subscriptions and some issues with topic aliases.

After some internal discussion, we are not convinced that this is a problem that the library should deal with, as it is possible to resolve this issue without modifying the library code.

In our case, in the `connect_handler` we simply start another task, but save the task reference so that we can cancel it if needed. But there is an argument to be made, that this is something the library can also do.

We are interested in knowing your thoughts on this. If this is something that you think should be done by the library, we are happy to implement and resolve this as part of our MQTTv5 implementation.

**Comment by peterhinch** [comment]
I've given this some thought and I agree that this should be handled by the application. Depending on the application, outright cancellation may not be correct - some other response might be required. Handling the case in the library would then require some kind of opt-out.

From your description above I get the impression you're using the callback-based interface. Have you considered using the event-based variant? It might lead to cleaner code for handling this kind of case.

**Comment by bobveringa** [comment]
Good to know we are aligned on how to proceed here.

We are indeed using the callback-based interface. I have given some thought to moving over, but our internal libraries and architecture are not set up for this at the moment. But I have noted it down as something for us to look into.
