### ISSUE TITLE
await client.connect() error in documented tutorial

### ISSUE THREAD

**Issue by RobinMosedale** [peterhinch/micropython-mqtt#15]
https://www.raspberrypi.org/forums/viewtopic.php?f=32&t=243760
refers.

"async def main(client):
        await client.connect()
        n=0
"
fails with syntax error:-

"import asyncmqtttest.py
 Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "asyncmqtttest.py", line 39
 SyntaxError: invalid syntax"

Not good enough to post unvalidated code or faulty undocumented implementation.

**Comment by peterhinch** [comment]
I cannot replicate this fault. The code posted does not produce a syntax error here.

**Comment by rroemhild** [comment]
I can confirm that your code has no syntax error. You'll get this error when you run your code with python2, because python2 has no `await` keyword but that's the only syntax problem I can see.

**Comment by peterhinch** [comment]
This library is intended to run under MicroPython on a microcontroller with WiFi capability: namely ESP8266, ESP32 or Pyboard D.

**Comment by RobinMosedale** [comment]
It is micropython on esp32, with the modules loaded as indicated in your guide.

I’ll double check versions of modules later

**Comment by RobinMosedale** [comment]
Peter,

thank you for your time.

It seems a hard syntax error on mine

The only module that supports a version number is the os via import etc:-
os sysname=esp32 release 1.10.0 version v1.10-311ge38c68310-dirty

none of the other modules support reporting versions either using upip or via a version object

machine is umachine
socket is usocket
network is network
here is uasyncio:-
>>> help(uasyncio)
object <module 'uasyncio' from '/lib/uasyncio/__init__.py'> is of type module
  log -- None
  IOWrite -- <class 'IOWrite'>
  select -- <module 'uselect'>
  Task -- <function Task at 0x3ffc49b0>
  IORead -- <class 'IORead'>
  PollEventLoop -- <class 'PollEventLoop'>
  ensure_future -- <function ensure_future at 0x3ffc4980>
  StreamReader -- <class 'StreamReader'>
  IOReadDone -- <class 'IOReadDone'>
  uerrno -- <module 'uerrno'>
  open_connection -- <generator>
  start_server -- <generator>
  EventLoop -- <class 'EventLoop'>
  StopLoop -- <class 'StopLoop'>
  ucollections -- <module 'ucollections'>
  StreamWriter -- <class 'StreamWriter'>
  time -- <module 'utime'>
  uasyncio -- <module 'uasyncio' from '/lib/uasyncio/__init__.py'>
  cancel -- <function cancel at 0x3ffc47d0>
  sleep -- <generator>
  utimeq -- <module 'utimeq'>
  sleep_ms -- <SleepMs object at 3ffc47b0>
  CancelledError -- <class 'CancelledError'>
  __file__ -- /lib/uasyncio/__init__.py
  SysCall1 -- <class 'SysCall1'>
  wait_for_ms -- <generator>
  TimeoutError -- <class 'TimeoutError'>
  _socket -- <module 'usocket'>
  SleepMs -- <class 'SleepMs'>
  set_debug -- <function set_debug at 0x3ffc3990>
  SysCall -- <class 'SysCall'>
  coroutine -- <function coroutine at 0x3ffc4850>
  DEBUG -- 0
  __name__ -- uasyncio
  IOWriteDone -- <class 'IOWriteDone'>
  type_gen -- <class 'generator'>
  core -- <module 'uasyncio.core' from '/lib/uasyncio/core.py'>
  __path__ -- /lib/uasyncio
  wait_for -- <function wait_for at 0x3ffc4840>
  TimeoutObj -- <class 'TimeoutObj'>
  get_event_loop -- <function get_event_loop at 0x3ffc4860>
>>> 
MPY: soft reboot
MicroPython v1.10-331-ge38c68310-dirty on 2019-05-09; ESP32 module with ESP32
Type "help()" for more information.
>>> 

uasyncio was installed via:-
repl>>
        import upip
        upip install(‘micropython-asyncio’)
        upip isntall(‘micropython-pkg_resources’)


So there is no ‘await’ object/function.
If you look at the code in my module you’ll see as you’re perfectly aware 1 await functions.
the error is not reported in the previous definition:-

“async def conn_hann(client):
        await client.subscribe('testTopic',1)”

but points to the one in the second definition:-

“async def main(client):
        await client.connect()
        n=0
        while True:
                await asyncio.sleep(5)
                print('publish',n)
                #If the wifi is down the following will pause for the duration.
                await client.publish('result','{}'.format(n),qos=1)
                n +=1”

BUT ALL OF THAT IS NONESENSE, there’s no await function definition.

So I suspect that I have a uasyncio which is renegade.

Could you please advise where I might download and safely install the relevent file variants for achieving the desired reult, Peter

Thank you
Robin



Here is the module

from machine import Pin
import socket
import sys
import network
import time

internalled=Pin(2,Pin.OUT)
externalled=Pin(4,Pin.OUT)


station=network.WLAN(network.STA_IF)
station.active(True)
station.connect("TP-LINK_EB850C", "ju87bstuka")
while (not (station.isconnected())):
        print("waiting to Connect")
        print (station.ifconfig())
        time.sleep(1)
station.ifconfig()
pin2.on()
time.sleep(1)
pin4.on()
pin2.off()
Time.sleep(1)
print ("Connected")
pin4.off()

from mqtt_as import MQTTClient
from config import config
import uasyncio as asyncio
SERVER='192.168.1.241'

def callback(topic,msg):
        print((topic,msg))

async def conn_hann(client):
        await client.subscribe('testTopic',1)

async def main(client):
        await client.connect()
        n=0
        while True:
                await asyncio.sleep(5)
                print('publish',n)
                #If the wifi is down the following will pause for the duration.
                await client.publish('result','{}'.format(n),qos=1)
                n +=1

config['subs_cb'] = callback
config['connect_coro'] = conn_han
config['server'] = SERVER

MQTTClient.DEBUG = True #Optional: print diagnostic messages
client=MQTTClient(config)
loop=asyncio.get.event_loop()
try:
        loop.run_until_complete(main(client))
finally:
        client.close() #Prevent LmacRxBlk:1 errors

**Comment by peterhinch** [comment]
I think you are right and you have a uasyncio version issue.

I suggest you use the latest release build (V1.11) of firmware here [for a board with no SPIRAM](https://micropython.org/resources/firmware/esp32-20190529-v1.11.bin) or here [if you have SPIRAM](https://micropython.org/resources/firmware/esp32spiram-20190529-v1.11.bin). These builds have uasyncio ready installed. Firmware installation instructions are [here](https://micropython.org/download#esp32).

**Comment by RobinMosedale** [comment]
Thank you Peter, that’s kind.

I’ll report back.
Robin

**Comment by RobinMosedale** [comment]
Clean erase
reburn with your link
copied program across
“/home/pi/micropython> repl
Entering REPL. Use Control-X to exit.
>
MicroPython v1.11 on 2019-05-29; ESP32 module with ESP32
Type "help()" for more information.
>>> 
>>> import asyncmqtttest.py
I (469185) phy: phy_version: 4007, 9c6b43b, Jan 11 2019, 16:45:07, 0, 0
waiting to Connect
('0.0.0.0', '0.0.0.0', '0.0.0.0', '0.0.0.0')
waiting to Connect
('0.0.0.0', '0.0.0.0', '0.0.0.0', '0.0.0.0')
waiting to Connect
('0.0.0.0', '0.0.0.0', '0.0.0.0', '192.168.1.254')
Connected
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "asyncmqtttest.py", line 28, in <module>
  File "mqtt_as.py", line 13, in <module>
ImportError: no module named 'uasyncio”"


Usyncio is supposed to be included in the base build, isn’t it?

Robin

**Comment by RobinMosedale** [comment]
The pyboard looks like this:-
/home/pi/micropython/async_mqtt> ls /pyboard
asyncmqtttest.py config.py        mqtt_as.py      
boot.py          ledflash.py     
/home/pi/micropython/async_mqtt>

**Comment by RobinMosedale** [comment]
>>> help('modules')
__main__          framebuf          socket            upip
_boot             gc                ssl               upip_utarfile
_onewire          hashlib           struct            upysh
_thread           heapq             sys               urandom
_webrepl          inisetup          time              ure
apa106            io                ubinascii         urequests
array             json              ucollections      uselect
binascii          machine           ucryptolib        usocket
btree             math              uctypes           ussl
builtins          micropython       uerrno            ustruct
cmath             neopixel          uhashlib          utime
collections       network           uhashlib          utimeq
dht               ntptime           uheapq            uwebsocket
ds18x20           onewire           uio               uzlib
errno             os                ujson             webrepl
esp               random            umqtt/robust      webrepl_setup
esp32             re                umqtt/simple      websocket_helper
flashbdev         select            uos               zlib
Plus any modules on the filesystem

**Comment by RobinMosedale** [comment]
>>> help('modules')
__main__          framebuf          socket            upip
_boot             gc                ssl               upip_utarfile
_onewire          hashlib           struct            upysh
_thread           heapq             sys               urandom
_webrepl          inisetup          time              ure
apa106            io                ubinascii         urequests
array             json              ucollections      uselect
binascii          machine           ucryptolib        usocket
btree             math              uctypes           ussl
builtins          micropython       uerrno            ustruct
cmath             neopixel          uhashlib          utime
collections       network           uhashlib          utimeq
dht               ntptime           uheapq            uwebsocket
ds18x20           onewire           uio               uzlib
errno             os                ujson             webrepl
esp               random            umqtt/robust      webrepl_setup
esp32             re                umqtt/simple      websocket_helper
flashbdev         select            uos               zlib
Plus any modules on the filesystem

**Comment by peterhinch** [comment]
Sorry, Robin. I was wrong about **uasyncio** being pre-installed: evidently it is not on ESP32.

I have just gone through the following procedure with an ESP32 reference board (no SPIRAM).

- Erased the flash.
- Installed release build V1.11.
- Ran a connect script to connect to my WiFi.
- Issued:

```python
import upip
upip.install('micropython-uasyncio')
```
In the **mqtt_as** directory I edited **config.py** for my WiFi and broker credentials (my broker is a Pi running mosquitto).

I then copied the following files to the ESP32:
- mqtt_as.py
- range.py
- config.py

At the REPL I then ran
```python
import range
```
This ran correctly.

I suggest you follow these steps to establish a working system, then start to develop your own application.

As a general point I would let the mqtt_as library perform the connection (as per the examples) rather than coding your own explicit connection routine, which is duplicating existing functionality.

I hope this helps.

**Comment by RobinMosedale** [comment]
But Peter, that's exactly what has been installed:-
now upip syntax has been corrected now getting other errors
see below for upip error + micropython version.

pi@PI3:~ $ cd micropython
pi@PI3:~/micropython $ rshell --buffer-size=30 --editor nano -p /dev/ttyUSB0 -a
Using buffer-size of 30
Connecting to /dev/ttyUSB0 (buffer-size 30)...
Trying to connect to REPL  connected
Testing if ubinascii.unhexlify exists ... Y
Retrieving root directories ... /boot.py/ /asyncmqtttest.py/ /ledflash.py/ /mqtt_as.py/ /config.py/
Setting time ... Jul 22, 2019 12:56:40
Evaluating board_name ... pyboard
Retrieving time epoch ... Jan 01, 2000
Welcome to rshell. Use Control-D (or the exit command) to exit rshell.
/home/pi/micropython> repl
Entering REPL. Use Control-X to exit.
>
MicroPython v1.11 on 2019-05-29; ESP32 module with ESP32
Type "help()" for more information.
>>> 
>>> import upip
>>> upip.install('micropython-uasyncio')
Installing to: /lib/
Error installing 'micropython-uasyncio': list index out of range, packages may be partially installed

**Comment by RobinMosedale** [comment]
As to upip syntax, I'd never have guessed that. All flavour of various formats in micropython website and not any indication of which applies to which version. Strangely, my original syntax worked, but no longer.

**Comment by peterhinch** [comment]
Are you sure you had a working internet connection? Alas the error messages from upip are unhelpful.

upip changed with version 1.11. Prior to that version it would install library modules which required the Pycopy fork of MicroPython. The new version will install compatible versions if they exist. This probably explains why you were having problems, and you need to be sure that any incompatible libraries are removed.

So I suggest you uninstall everything (or erase flash, as I did), then copy my instructions above. It worked here and I can see no reason why it shouldn't work for you.

**Comment by RobinMosedale** [comment]
Many thanks Peter.
Although I'd erased and reinstalled the v1.11 there were errors.
So rather than the plain v1.11 there following was installed on a clean board
esp32-20190722-v1.11-167-g331c224e0.bin (latest)
Happy to say, wifi connected upip worked as desired, and your files copied across
AND
Success
range program works fine with my Mosquitto publishing on Pi3.

So very many thanks for your patience.
Now building on this to experiment with asynchronous routines

Robin
