### ISSUE TITLE
New location of mqtt_as.py

### ISSUE THREAD

**Issue by sgbaird** [peterhinch/micropython-mqtt#155]
Typically, I've been linking to the mqtt_as.py file and the corresponding README. However, somebody brought to my attention that these links are no longer valid. I'm assuming this has something to do with the restructure into a Python package that I saw mentioned. I poked around the repository a little bit, but had trouble finding the file again. Could you help clarify? (Sorry if I'm missing it in an obvious place). On a related note, should I recommend that people install with `mip` for example?

Thanks @Neil-YL for pointing out.

**Comment by sgbaird** [comment]
Looks like the main README link on the GitHub homepage/readme also gives a 404 error.

![Screenshot_20241001-112143.png](https://github.com/user-attachments/assets/ffff54db-e5cb-4022-825d-b19e61493c80)

**Comment by peterhinch** [comment]
I am sorry for the confusion. The reorganisation served two purposes:
1. To retire the `bridge` project. Given modern hardware, anyone wanting WiFi connectivity would buy a platform that supported it. Retiring `bridge` enabled the repo to be tidied up.
2. To convert `mqtt_as` to a Python package. This was preparatory to further improvements such as adding MQTT V5 support, plus other improvements that are in the pipeline. As you have discovered, the main module is in `__init__.py`.

I'm confused by your report of broken links. Please could you clarify any links that need fixing.

**Comment by sgbaird** [comment]
Thanks for clarifying! Would you suggest using `mip install` then?

https://github.com/peterhinch/micropython-mqtt/blob/0d759397ef4f80d48f8a419d22d0a40d5dc72526/README.md?plain=1#L24 resolves to 404: https://github.com/peterhinch/micropython-mqtt/blob/README.md (this is the link that's actually displayed at https://github.com/peterhinch/micropython-mqtt)
