### ISSUE TITLE
Contact you? trying Your code on ESP32

### ISSUE THREAD

**Issue by Wessix** [peterhinch/micropython-mqtt#2]
Hi sorry to contact you that way.
I'm trying out your umqtt asyncio code on esp32 and would like to contact you. If you are in any IRC Chat oder Skype or something else, could you let me know?
I'm not a python professional but with some trial and error i got a dht22 sensor and Oled Display to run and make the esp32 report to Home Assistant with mqtt simple.  
After some tests i figured out, that if the broker goes down for some reason, the mqtt simple fails.
With your code this works. But when i simulated a wlan shutdown,  my esp32 froze at reconnecting.
On Skype you could find me as w-e-s-s-i-x-1    (without the "-").

**Comment by peterhinch** [comment]
The ESP32 MicroPython port is still somewhat experimental. You'll see some of the difficulties I encountered [here](https://github.com/micropython/micropython-esp32/issues/167). So my code includes a number of arbitrary hacks to make it run on ESP32. It rather sounds as if a firmware change may have actually made it worse: I did test with sudden and gradual failures of WiFi connectivity.

I am currently busy and am unlikely to be able to look at this until early in the new year. But I do plan to review its operation on ESP32 with a view to removing the hacks and re-testing.

The best way to contact me is via a personal message in [the forum](https://forum.micropython.org/) where my username is pythoncoder.

**Comment by Wessix** [comment]
Ok thx for the quick reply, ok so I'll  open a user account there. I wrote cause i read in one thread that you would appreciate if somone can test your code on esp32.
Well before Christmas its busy for all of us, so no Problem.
I would dig further into the problem if i had an error code, but the console throws no error, just freezes.

So see you there.

**Comment by peterhinch** [comment]
I trust you read the [link](https://github.com/micropython/micropython-esp32/issues/167) I gave you - it sounds very much like your problem which @dpgeorge has confirmed still exists. Until the underlying firmware is fixed I think we're stuck.
