### ISSUE TITLE
disconnect() doesn't work, triggers reconnect

### ISSUE THREAD

**Issue by kevinkk525** [peterhinch/micropython-mqtt#31]
The disconnect method doesn't work because it just closes the socket but keep_connected is still running and triggers a reconnect. _has_connected would need to be reset and _keep_connected canceled.
I might create a PR the next days if you like.

**Comment by goatchurchprime** [comment]
Does it use the cancellable feature from here?
    https://github.com/peterhinch/micropython-async/blob/master/PRIMITIVES.md#4-task-cancellation
So many modules floating about you can't tell what's in and what's out.

**Comment by kevinkk525** [comment]
It would use the uasyncio.cancel feature, which is described in the link you posted but could be implemented without a cancel feature too. Haven't looked into it too much yet.

**Comment by kevinkk525** [comment]
fixed via #32
