### ISSUE TITLE
keepalive race condition

### ISSUE THREAD

**Issue by tve** [peterhinch/micropython-mqtt#41]
Another nit ;-)

Unless the user explicitly sets `config['ping_interval']` the timeout where the `_keep_alive` starts a reconnection process is the same as the `keep alive` value set at the MQTT protocol level. This produces a bit of a race condition as to whom times out first.

Unless I'm missing something, the two effects of the keep alive mechanism at the MQTT level are for the broker to send the last will message when it discovers that the keep live timed out, and for the broker to close the connection when 1.5x the keep-alive times out. Nothing else.

So when the `_keep_alive` coro discovers a time-out there's a bit of a race condition between the client reconnecting and the broker discovering the time-out and triggering the last will message. If no last will message is set, the MQTT keep alive mechanism is really pretty irrelevant given the client-side timeout. IMHO for proper last will operation the coro's time-out should be shorter than the MQTT keep-alive time, which can be set explicitly using the `ping_interval` config param but that's not exactly obvious to someone that just naively sets the last will message.

**Comment by peterhinch** [comment]
Thank you for your comments. I will review this module in due course.

The new uasyncio is due for imminent release. I expect to be busy with that for some time, given that almost all my published code makes heavy use of it. My tutorial is also likely to need a substantial update.
