### ISSUE TITLE
Error 'module' object has no attribute 'Lock'

### ISSUE THREAD

**Issue by poerob** [peterhinch/micropython-mqtt#43]
Hello,

i tried to install and use the resilient mqtt library. As you described in your Guide, i installed uasyncio, uasyncio.synchro and uasyncio.queues [Link](https://github.com/peterhinch/micropython-async/blob/master/TUTORIAL.md#01-installing-uasyncio-on-bare-metal) and copied mqtt_as.py and config.py via mpfshell to the root directory. Unfortunately, im stuck with the error "'module' object has no attribute 'Lock'" when i call a test script. Looking at the code in mqtt_as, it seems this error comes from lock being not found in uasyncio. Can you help me with that? 

Anyway, thank you for the effort to create a resilient mqtt lib and the great documentation. I can't wait to start working with the library.

**Comment by kevinkk525** [comment]
The library got updated to support the new uasyncio version 3.0.0 that got merged in to micropython recently. If you use a daily build of the micropython firmware you don't need to install uasyncio and can remove all those module you installed.
If you are running an older version of micropython or want to keep using the old uasyncio version, then use this version of mqtt_as (before the commit that updated it to the new uasyncio version): https://github.com/peterhinch/micropython-mqtt/blob/ff6b5aa3121de1ea9ca6436f535f0817105cfadd/mqtt_as/mqtt_as.py

**Comment by poerob** [comment]
Hi kevin, thank you for your fast reply! Indeed, i did not use a daily build but a version from 2019 [Link](http://micropython.org/resources/firmware/esp32-idf3-20191220-v1.12.bin). I did not use the latest build by accident, thank you for the hint.
Anyway, installing uasyncio via upip leads to a old uasyncio version from June 2019 [Link](https://pypi.org/project/micropython-uasyncio/) compared to the latest available in the micropython GitHub Repo. Is that intention?

**Comment by poerob** [comment]
Just updated the Controller and now everything works fine. Thanks for the fast help!

**Comment by kevinkk525** [comment]
Glad you got it sorted out.

> Even if this has nothing todo with the mqtt lib, installing uasyncio via upip leads to a old uasyncio version from June 2019 Link compared to the latest available in the micropython GitHub Repo. Is that intention?
The version on pypip is not an official uasyncio version and doesn't even work on the official micropython. It's out of the control of the micropython contributors.

**Comment by peterhinch** [comment]
@kevinkk525 Just FYI that issue was fixed a while ago: `upip` first searches a database maintained by Damien, only if an item is not found does it look on PyPi. Consequently
```python
upip.install('micropython-uasyncio')
```
will install the old, official `uasyncio` (unless it's an old version of `upip`).

**Comment by kevinkk525** [comment]
Oh, thanks! I forgot upip was fixed that way by Damien. That's good.
