### ISSUE TITLE
int topic

### ISSUE THREAD

**Issue by jdtsmith** [peterhinch/micropython-mqtt#49]
Although the docs do mention "string topic", the in-built `MQTT.simple` allows integer topics as well, but this leads to an error with `mqtt_as`.

**Comment by peterhinch** [comment]
From [the spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349270) section 3.3.2.1:

> The Topic Name MUST be present as the first field in the PUBLISH Packet Variable header. It MUST be a UTF-8 encoded string [MQTT-3.3.2-1] as defined in section 1.5.3.

You can of course convert an integer to a string.

In general these queries would be better put in [the forum](http://forum.micropython.org/index.php) where they would be seen, and potentially answered, by more people. GitHub is really intended for bug reports.

**Comment by jdtsmith** [comment]
Of course I know how to work around it!  My only point is that if you are intending to have mqtt_as serve as a near drop-in replacement for the bundled  `umqtt.simple` (which presumably many will be porting from), it might be preferable to mirror its behavior, or at least provide a documentation warning for those who are porting.  Thanks.
