### ISSUE TITLE
Unicode letter in MQTT topic or message e.g. "°" lets crash publish()

### ISSUE THREAD

**Issue by Gert-Lumpy** [peterhinch/micropython-mqtt#66]
This is reproducible output when having UTF letter in topic or msg:
WiFi not connected
Checking WiFi integrity.
Got reliable connection with IP 192.168.1.4
Connecting to broker.
Connected to broker.
Wifi is up
publish topic + msg  ['test/powersensor/temperature/°$unit', '°C']
Wifi is down
Connection error
WiFi not connected
Checking WiFi integrity.

In source code I could see that the length is derived from msg before sending.  May be the issue.

**Comment by peterhinch** [comment]
Messages should be bytes objects or strings comprising the first 128 Unicode code points (i.e. single byte characters).
