### ISSUE TITLE
How to subscribe in subs_cb?

### ISSUE THREAD

**Issue by Narsskrarc** [peterhinch/micropython-mqtt#67]
Hi all,

I try to setup an ESP32 which get its config from a mqtt topic.
So I subscribe the topic in the connect_coro.
When the message comes I want to subscribe other topics according to this message.
But how can I subscribe something in the subs_cb? It is no coroutine and when I try to await mqtt.subscribe() inside the subs_cb it isn't called at all.

What would be the right way to do that?

**Comment by peterhinch** [comment]
I've never tried that arrangement but I think it should work fine. I would do something like this. In the callback:
```python
if condition_is_met:
    asyncio.create_task(subscribe_to, topic, qos)
```
And then
```python
async def subscribe_to(topic, qos):
    await client.subscribe(topic, qos)
```

**Comment by Narsskrarc** [comment]
That sounds as a good idea. I will test it asap.
Thanks!

**Comment by Narsskrarc** [comment]
Well, I tested it now. ;-)
A little change: it has to be
`asyncio.create_task(subscribe_to(topic, qos))`
...and then this works. Thanks again!

**Comment by peterhinch** [comment]
Yes. Brain-fade there on my part :)
