### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by bobveringa** [peterhinch/micropython-mqtt#80]
Most of the improvements discussed in #75 have now been merged. Should the version number be updated to reflect these changes?

I have a few improvements in the works, such as the continuation of #24 as our custom `wifi_connect function` already does this. However, I have not yet started on this and I would to put it through some validation before opening a PR.

**Comment by peterhinch** [comment]
Indeed - once we've resolved the issue of whether to change `._keep_alive`. Also some doc changes I'm planning.
