### ISSUE TITLE
How does one install this?  I don't see it listed in Thonny package list?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [peterhinch/micropython-mqtt#85]
How does one install this?  I don't see it listed in Thonny package list?

**Comment by peterhinch** [comment]
Please see [the docs](https://github.com/peterhinch/micropython-mqtt/blob/master/mqtt_as/README.md#22-installation). You just have to copy the two required files to your device's filesystem.

**Comment by Jibun-no-Kage** [comment]
When I copied config.py and mqtt_as.py to the Pico, then I overwrite the firmware image, and Thonny throws up a dialog asking for Micropython to be installed again.  Then I realized I need to get them into the actual Pico file system.  I used Thonny file view to do this, so now I can import them as expected.

Seems odd that Thonny package management can see the your package?  Say like it does for umqtt simple/robust[2] packages?

I sentence or two in the documentation on how to copy files to Pico file system would be suggestion, because as a new user, your documentation left me completely lost, There is a big difference between just copying over the firmware image to a Pico versus accessing the Pico local file system.  Just making that point would be a big help to new users.

**Comment by peterhinch** [comment]
I don't use Thonny but it sounds like it can only see packages in the official library. `mqtt_as` is not an official library.

Re the docs, section 2.2 explicitly says for platforms other than ESP8266:
> On other platforms simply copy the Python source to the filesystem (items 1 and 2 above as a minimum).

If, to a new user, it is unclear how to do this, it is the Pico or Thonny that needs additional documentation.

**Comment by Jibun-no-Kage** [comment]
I agree in part with you suggestion about the documentation, but I also see the logic in that if you added a sentence or two warning a new user, that would be of great benefit.  A suggestion.  Maybe, this discourse, will serve to help others.

That aside, thanks for responding, always appreciated when solutions are actively supported!  In a couple of days, I should have my MQTT design working.  I have a couple of design questions already, best practice type of thing, but until I spend some real time with your implementation, I suspect the best practice questions I have may be answered.
