### ISSUE TITLE
Pycom WiFi connection

### ISSUE THREAD

**Issue by DanielIbaseta** [peterhinch/micropython-mqtt#9]
When using your library in a Pycom board, the WiFi connection process and methods are different from a regular ESP32, so it returns an exception. I could modify your code in order to detect hardware and use the appropriate connection method, but I think it would be nice to have it in the original library.

**Comment by peterhinch** [comment]
I'm not in a position to support PyCom hardware. I possess none of their kit. Further, the purpose of the library is to implement a resilient connection and I doubt if it's possible owing to [this issue](https://github.com/micropython/micropython-esp32/issues/167) which I believe nobody has resolved. Unless PyCom have, and it's not been shared,

I am planning a review of this library when the Pyboard D emerges: unless there is some progress on the above issue I may remove ESP32 support (along with Sonoff which was unusable). The ESP32 code has a lot of hacks which proved empirically necessary but it's pretty nasty. I'm keen to remove all the arbitrary hacks.

By contrast ESP8266 is rock-solid and hopefully so will be the D series. For obvious reasons my intention is to support only hardware which I've proven to be capable of resilience.

If you want to develop this for PyCom ESP32 feel free but be aware that proving resilience requires a lot of time consuming testing. If you can achieve a truly resilient outcome I would be very interested indeed to see it.
