### ISSUE TITLE
Is it possible to use your driver with a WiFi manager library?

### ISSUE THREAD

**Issue by faisal-saddique** [peterhinch/micropython-mqtt#96]
I was thinking of using a WiFi manager library like [this one](https://github.com/tayfunulu/WiFiManager) with your async MQTT driver but wasn't sure if I could do it because the constructor of mqtt_as asks for WiFi credentials to connect to, which I don't have hardcoded in my code. Any help would be highly appreciated.

**Comment by ebolisa** [comment]
I use it all the time!! Just create a function to read the credentials from wifi.dat when needed 😉

**Comment by faisal-saddique** [comment]
Thank you for answering, @ebolisa!

I was also thinking of doing the same. But let's say if we have more than 1 credentials stored in the wifi.dat file, what be the approach then?

**Comment by ebolisa** [comment]
Just need to cycle trough them. In a project I’m saving the ip, subnet, dns, etc as well. In another, I’m saving the Blynk token. Of course, I had to modify the wifimng.py to collect additional data.

**Comment by faisal-saddique** [comment]
Okay, thank you!
